AWSTemplateFormatVersion: 2010-09-09
Description: Test

Resources:
  LoggingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ewelists-pipeline-test
      AccessControl: LogDeliveryWrite
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
