AWSTemplateFormatVersion: "2010-09-09"
Description: Performs the one time task of configuring the API gateway CloudWatch log role

Parameters:
  RoleName:
    Description: API Gateway Cloudwatch log role name
    Type: String
    Default: sudokuless-api-cloudwatch-role

Resources:
  ApiRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - apigateway.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: ApiServiceRolePolicy
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:DescribeLogGroups
              - logs:DescribeLogStreams
              - logs:PutLogEvents
              - logs:GetLogEvents
              - logs:FilterLogEvents
            Resource: "*"
          Version: '2012-10-17'

  ApiSettings:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt ApiRole.Arn
