AWSTemplateFormatVersion: 2010-09-09
Description: Creates backend dynamodb tables.
Parameters:
  Environment:
    Description: Environment type.
    Default: test
    Type: String
    AllowedValues:
      - prod
      - staging
      - dev
      - test
    ConstraintDescription: must specify prod, staging, dev or test.

Resources:
  ListsTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub "lists-${Environment}"
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: email
          AttributeType: S
        - AttributeName: reservationId
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: True
      GlobalSecondaryIndexes:
        - IndexName: userId-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: PK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: reservationId-index
          KeySchema:
            - AttributeName: reservationId
              KeyType: HASH
            - AttributeName: PK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: email-index
          KeySchema:
            - AttributeName: email
              KeyType: HASH
            - AttributeName: PK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: SK-index
          KeySchema:
            - AttributeName: SK
              KeyType: HASH
            - AttributeName: PK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  ProductsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub "products-${Environment}"
      AttributeDefinitions:
        - AttributeName: productId
          AttributeType: S
        - AttributeName: productUrl
          AttributeType: S
      KeySchema:
        - AttributeName: productId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: True
      GlobalSecondaryIndexes:
        - IndexName: producturl-index
          KeySchema:
            - AttributeName: productUrl
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  NotFoundTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub "notfound-${Environment}"
      AttributeDefinitions:
        - AttributeName: productId
          AttributeType: S
      KeySchema:
        - AttributeName: productId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: True

Outputs:
  ListsTable:
    Description: Table name.
    Value: !Ref ListsTable
    Export:
      Name: !Sub 'ListsTable-${Environment}'

  ProductsTable:
    Description: Table name.
    Value: !Ref ProductsTable
    Export:
      Name: !Sub 'ProductsTable-${Environment}'

  NotFoundTable:
    Description: Table name.
    Value: !Ref NotFoundTable
    Export:
      Name: !Sub 'NotFoundTable-${Environment}'
