AWSTemplateFormatVersion: 2010-09-09
Description: Creates pipeline artifact bucket in desired region.
Parameters:
  PipelineName:
    Type: String
    Description: Name of application used to describe resources.
    AllowedPattern: "^[-a-z0-9]*$"
    ConstraintDescription: Application name can include numbers, lowercase letters, and hyphens (-).

Resources:
  PipelineArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'pipeline-ewelists-${PipelineName}-${AWS::Region}-artifacts'
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      LifecycleConfiguration:
        Rules:
          - Id: Build logs expiration
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
            ExpirationInDays: 180
            Prefix: !Sub 'pipeline-${PipelineName}-${AWS::Region}-artifacts*'
            Status: Enabled

Outputs:
  PipelineArtifactBucketName:
    Description: The name of the pipeline artifact bucket.
    Value: !Ref PipelineArtifactBucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'

  PipelineArtifactBucketArn:
    Description: The name of the pipeline artifact bucket.
    Value: !GetAtt PipelineArtifactBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-Arn'
