AWSTemplateFormatVersion: 2010-09-09
Description: SSL certificate used in cloudfront distribution, must be created in us-east-1
Parameters:
  DomainName:
    Description: Domain name for your website (example.com)
    Type: String
    AllowedPattern: "^[a-z0-9-]*.com$"
    ConstraintDescription: Must be a web domain, ending in .com. Can include lower case letters, numbers and hypens.
    Default: ewelists.com
  CoUkDomainName:
    Description: Domain name for your website (example.co.uk)
    Type: String
    AllowedPattern: "^[a-z0-9-]*.co.uk$"
    ConstraintDescription: Must be a web domain, ending in .co.uk. Can include lower case letters, numbers and hypens.
    Default: ewelists.co.uk
  HostedZone:
    Description: HostedZoneID of Sub domain.
    Type: String
  Environment:
    Description: Environment type.
    Default: test
    Type: String
    AllowedValues:
      - prod
      - staging
      - dev
      - test
    ConstraintDescription: must specify prod or test.

Conditions:
  Prod: !Equals [ !Ref Environment, prod ]

Resources:
  SslCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !If [Prod, !Ref DomainName, !Sub "${Environment}.${DomainName}"]
      SubjectAlternativeNames:
        - !If [Prod, !Ref DomainName, !Sub "${Environment}.${DomainName}"]
        - !If [Prod, !Sub "*.${DomainName}", !Sub "*.${Environment}.${DomainName}"]
        - !If [Prod, !Ref CoUkDomainName, !Sub "${Environment}.${CoUkDomainName}"]
        - !If [Prod, !Sub "*.${CoUkDomainName}", !Sub "*.${Environment}.${CoUkDomainName}"]
      DomainValidationOptions:
        - DomainName: !If [Prod, !Ref DomainName, !Sub "${Environment}.${DomainName}"]
          HostedZoneId: !Ref HostedZone
      ValidationMethod: "DNS"

Outputs:
  CertificateArn:
    Description: ARN of the ACM (SSL) Certificate
    Value: !Ref SslCertificate
